export enum FranceDepartementCode {
  HautesAlpes = "05",
  AlpesMaritimes = "06",
  Calvados = "14",
  Charente = "16",
  Creuse = "23",
  Gers = "32",
  Herault = "34",
  Landes = "40",
  Loire = "42",
  Oise = "60",
  PuyDeDome = "63",
  Rhone = "69",
  SaoneEtLoire = "71",
  Sarthe = "72",
  Vaucluse = "84",
  HautsDeSeine = "92",
}
