"use strict"
Object.defineProperty(exports, "__esModule", {value: true})
var angular = require("angular")
var UdbService_1 = require("./UdbService")
var UdbController_1 = require("./UdbController")
var WebFileInput_1 = require("./WebFileInput")
var Logger_1 = require("../Logger")
angular.module("rr0")
  .constant("DEBUG", false)
  .constant("verbose", true)
  .service("udbService", UdbService_1.UdbService)
  .service("logger", Logger_1.Logger)
  .service("webFileInput", WebFileInput_1.WebFileInput)
  .service("webReadLine", UdbService_1.WebReadLine)
  .controller("UdbController", UdbController_1.UdbController)
//# sourceMappingURL=ngUdb.js.map
