export enum Occupation {
  actor = "actor",
  artist = "artist",
  anthropologist = "anthropologist",
  archeologist = "archeologist",
  astronaut = "astronaut",
  astronomer = "astronomer",
  astrologist = "astrologist",
  astrophysicist = "astrophysicist",
  barman = "barman",
  biologist = "biologist",
  biochemist = "biochemist",
  biophysicist = "biophysicist",
  bishop = "bishop",
  botanist = "botanist",
  cameraman = "cameraman",
  chemist = "chemist",
  contactee = "contactee",
  cryptozoologist = "cryptozoologist",
  dentist = "dentist",
  director = "director",
  engineer = "engineer",
  ethnologist = "ethnologist",
  exobiologist = "exobiologist",
  farmer = "farmer",
  flightAttendant = "flightAttendant",
  geologist = "geologist",
  geophysicist = "geophysicist",
  geographer = "geographer",
  historian = "historian",
  houseWife = "houseWife",
  illusionist = "illusionist",
  journalist = "journalist",
  lawyer = "lawyer",
  librarian = "librarian",
  mathematician = "mathematician",
  mechanic = "mechanic",
  meteorologist = "meteorologist",
  military = "military",
  musician = "musician",
  neurologist = "neurologist",
  neuroscientist = "neuroscientist",
  neuropsychiatrist = "neuropsychiatrist",
  nurse = "nurse",
  oceanographer = "oceanographer",
  parapsychologist = "parapsychologist",
  philosopher = "philosopher",
  painter = "painter",
  pilot = "pilot",
  photographer = "photographer",
  physician = "physician",
  physicist = "physicist",
  politician = "politician",
  policeman = "policeman",
  priest = "priest",
  producer = "producer",
  psychologist = "psychologist",
  psychiatrist = "psychiatrist",
  radioastronomer = "radioastronomer",
  radioamateur = "radioamateur",
  salesman = "salesman",
  sailor = "sailor",
  sociologist = "sociologist",
  softwareEngineer = "softwareEngineer",
  stuntman = "stuntman",
  taxiDriver = "taxiDriver",
  teacher = "teacher",
  telegrapher = "telegrapher",
  truckDriver = "truckDriver",
  ufologist = "ufologist",
  /**
   * Firsthand UFO witness.
   */
  ufoWitness = "ufoWitness",
  /**
   * Second-hand UFO witness.
   */
  ufoWitness2 = "ufoWitness2",
  worker = "worker",
  writer = "writer"
}
