export enum NuforcShape {
  Cigar = "Cigar",
  Circle = "Circle",
  Chevron = "Chevron",
  Cone = "Cone",
  Cube = "Cube",
  Cylinder = "Cylinder",
  Changing = "Changing",
  Diamond = "Diamond",
  Disk = "Disk",
  Flash = "Flash",
  Formation = "Formation",
  Light = "Light",
  Orb = "Orb",
  Oval = "Oval",
  Other = "Other",
  Rectangle = "Rectangle",
  Sphere = "Sphere",
  Star = "Star",
  Teardrop = "Teardrop",
  Triangle = "Triangle",
  Unknown = "Unknown"
}
