export enum NuforcCountry {
  Algeria = "Algeria",
  Australia = "Australia",
  Brazil = "Brazil",
  Canada = "Canada",
  Colombia = "Colombia",
  DominicanRepublic = "Dominican Republic",
  Germany = "Germany",
  India = "India",
  Mexico = "Mexico",
  NewZealand = "New Zealand",
  Panama = "Panama",
  Peru = "Peru",
  Philippines = "Philippines",
  Seychelles = "Seychelles",
  SouthKorea = "South Korea",
  UnitedKingdom = "United Kingdom",
  Unspecified = "Unspecified",
  USA = "USA"
}
