export enum UsaCountyCode {
  arlington = "arlington",
  burlington = "burlington",
  carbon = "carbon",
  chaves = "chaves",
  dane = "dane",
  elkhart = "elkhart",
  fayette = "fayette",
  geneva = "geneva",
  guilford = "guilford",
  kalamazoo = "kalamazoo",
  pinellas = "pinellas",
  pierce = "pierce",
  mason = "mason",
  monroe = "monroe",
  niagara = "niagara",
  middlesex = "middlesex",
  rutland = "rutland",
  sandiego = "sandiego",
  scottsBluff = "scottsBluff",
  stThomas = "stThomas",
  tarrant = "tarrant",
  uintah = "uintah",
  westmoreland = "westmoreland",
  whitley = "whitley",
}
