export enum UsaCountyCode {
  arlington = "arlington",
  burlington = "burlington",
  chaves = "chaves",
  elkhart = "elkhart",
  fayette = "fayette",
  geneva = "geneva",
  guilford = "guilford",
  pinellas = "pinellas",
  pierce = "pierce",
  mason = "mason",
  monroe = "monroe",
  niagara = "niagara",
  westmoreland = "westmoreland",
  sandiego = "sandiego",
  tarrant = "tarrant",
  whitley = "whitley",
  scottsBluff = "scottsBluff",
  middlesex = "middlesex",
  kalamazoo = "kalamazoo",
}
