### Find cases between 01/03/1977 and 31/03/1977
GET https://geipan.fr/fr/recherche/cas?field_agregation_index_value=&field_departement_target_id=&
    field_latitude_value%5Bmin%5D=&field_latitude_value%5Bmax%5D=&field_longitude_value%5Bmin%5D=&
    field_longitude_value%5Bmax%5D=&field_date_d_observation_value%5Bmin%5D=1977%2F03%2F01&
    field_date_d_observation_value%5Bmax%5D=1977%2F03%2F31&field_type_de_cas_target_id=All&field_phenomene_target_id=&
    field_document_existe_ou_pas_value=All&select-category-export=nothing

### Individual case
GET https://geipan.fr/fr/cas/1977-10-00438?customGetLattitude=46.124763699209396&customGetLongitude=2.406005859375&
    customGetZoom=6&field_agregation_index_value=&field_date_d_observation_value%5Bmax%5D=1977%2F03%2F31&
    field_date_d_observation_value%5Bmin%5D=1977%2F03%2F01&field_departement_target_id=&
    field_document_existe_ou_pas_value=All&field_latitude_value%5Bmax%5D=&
    field_latitude_value%5Bmax%5D=50.52739681329302&field_latitude_value%5Bmin%5D=&
    field_latitude_value%5Bmin%5D=41.72213058512578&field_longitude_value%5Bmax%5D=&
    field_longitude_value%5Bmax%5D=7.998046875000001&field_longitude_value%5Bmin%5D=&
    field_longitude_value%5Bmin%5D=-3.1860351562500004&field_phenomene_target_id=&field_type_de_cas_target_id=All&
    page=0&select-category-export=nothing
